<?php

declare(strict_types=1);

namespace Gaffer\Ai;

use Gaffer\Gaffer;
use Gaffer\Paths;

/**
 * Assembles the guidelines: Gaffer's (overridable per file by the theme's
 * .ai/guidelines/), plugin guidelines for active plugins, the theme's own
 * guidelines, and the generated reference.
 */
final class Guidelines
{
    /** Gaffer's guidelines, in reading order. */
    private const array GAFFER = ['core', 'views', 'types', 'ajax', 'blocks', 'config', 'cli'];

    /** @param list<string> $plugins Active plugins with a guideline (e.g. "woocommerce") */
    public static function build(array $plugins): string
    {
        $parts = [];
        $overridden = [];

        foreach ([...self::GAFFER, ...array_map(static fn(string $p): string => "plugins/{$p}", $plugins)] as $name) {
            $theme = Paths::base(".ai/guidelines/{$name}.md");
            if (is_file($theme)) {
                $overridden[] = realpath($theme);
                $parts[] = (string) file_get_contents($theme);
            } elseif (is_file(self::gaffer($name))) {
                $parts[] = (string) file_get_contents(self::gaffer($name));
            }
        }

        foreach (self::theme_files() as $file) {
            if (!in_array(realpath($file), $overridden, true)) {
                $parts[] = (string) file_get_contents($file);
            }
        }

        $parts[] = Reference::build();

        return "# " . self::theme_name() . " — AI guidelines\n\n"
            . 'Generated by `php gaffer ai:update` (Gaffer ' . Gaffer::version() . '). Do not edit: '
            . "change the theme's `.ai/guidelines/*.md` (or Gaffer) and regenerate.\n\n"
            . (is_file(Paths::base('AGENTS_DEV.md')) ? "Working on this theme's own development? Also read `AGENTS_DEV.md`.\n\n" : '')
            . implode("\n\n", array_map(trim(...), $parts)) . "\n";
    }

    private static function gaffer(string $name): string
    {
        return dirname(__DIR__, 2) . "/resources/ai/guidelines/{$name}.md";
    }

    /**
     * Every .md under the theme's .ai/guidelines/, sorted (subdirectories too).
     *
     * @return list<string>
     */
    private static function theme_files(): array
    {
        $dir = Paths::base('.ai/guidelines');
        $files = [...glob("{$dir}/*.md") ?: [], ...glob("{$dir}/*/*.md") ?: []];
        sort($files);

        return $files;
    }

    private static function theme_name(): string
    {
        $style = Paths::base('style.css');
        if (is_file($style) && preg_match('/^[\s*]*Theme Name:\s*(.+)$/mi', (string) file_get_contents($style), $m)) {
            return trim($m[1]);
        }

        return basename(Paths::base());
    }
}
