<?php

declare(strict_types=1);

namespace Gaffer\Ai;

use FilesystemIterator;
use Gaffer\Paths;
use InvalidArgumentException;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

/**
 * Writes the generated guidelines and skills into the theme for the selected
 * agents, and keeps the theme's .gitignore in sync with what it writes.
 */
final class Installer
{
    private const string START = '<!-- gaffer:start -->';
    private const string END = '<!-- gaffer:end -->';

    /** Marks a skill directory as generated (so stale ones can be removed). */
    private const string SKILL_MARKER = '.gaffer-generated';

    /**
     * @param list<string> $agent_names
     * @param list<string> $plugins
     * @return list<string> files and directories written, relative to the theme
     */
    public static function update(array $agent_names, array $plugins): array
    {
        $agents = self::agents($agent_names);
        $written = [];

        $kept = ' (kept its existing content above the generated block: move it to .ai/guidelines/)';

        $written[] = 'AGENTS.md' . (self::write_marked('AGENTS.md', Guidelines::build($plugins)) ? $kept : '');

        foreach ($agents as $agent) {
            if ($agent->file !== null) {
                $written[] = $agent->file . (self::write_marked($agent->file, "@AGENTS.md\n") ? $kept : '');
            }
        }

        $skills = self::skills();
        foreach ($agents as $agent) {
            if ($agent->skills !== null) {
                self::write_skills($agent->skills, $skills);
                $written[] = "{$agent->skills}/ (" . count($skills) . ' skills)';
            }
        }

        self::gitignore($agents);

        return $written;
    }

    /**
     * @param list<string> $names
     * @return list<Agent>
     */
    public static function agents(array $names): array
    {
        $all = Agent::all();
        $unknown = array_diff($names, array_keys($all));
        if ($unknown !== []) {
            throw new InvalidArgumentException('Unknown agent(s): ' . implode(', ', $unknown) . '. Known: ' . implode(', ', array_keys($all)) . '.');
        }

        return array_map(static fn(string $name): Agent => $all[$name], $names);
    }

    /**
     * Skill directories by name: Gaffer's, overridden or extended by the theme's .ai/skills/.
     *
     * @return array<string, string>
     */
    private static function skills(): array
    {
        $skills = [];
        foreach ([dirname(__DIR__, 2) . '/resources/ai/skills', Paths::base('.ai/skills')] as $root) {
            foreach (glob("{$root}/*/SKILL.md") ?: [] as $file) {
                $skills[basename(dirname($file))] = dirname($file);
            }
        }
        ksort($skills);

        return $skills;
    }

    /** @param array<string, string> $skills */
    private static function write_skills(string $relative, array $skills): void
    {
        $target = Paths::base($relative);
        if (!is_dir($target)) {
            mkdir($target, 0755, true);
        }

        // Remove generated skills that no longer exist; leave the user's own alone.
        foreach (glob("{$target}/*/" . self::SKILL_MARKER) ?: [] as $marker) {
            if (!isset($skills[basename(dirname($marker))])) {
                self::remove(dirname($marker));
            }
        }

        foreach ($skills as $name => $source) {
            $dir = "{$target}/{$name}";
            if (is_dir($dir) && !is_file("{$dir}/" . self::SKILL_MARKER)) {
                continue; // a hand-made skill with the same name wins
            }
            self::remove($dir);
            self::copy($source, $dir);
            file_put_contents("{$dir}/" . self::SKILL_MARKER, "Generated by `php gaffer ai:update`; changes are overwritten.\n");
        }
    }

    /**
     * Writes content between the gaffer markers; anything outside them is kept.
     * A file without markers keeps its content and gets the block appended.
     *
     * @return bool whether the file had content of its own without markers
     */
    private static function write_marked(string $relative, string $content): bool
    {
        $file = Paths::base($relative);
        $block = self::START . "\n" . rtrim($content) . "\n" . self::END;
        $existing = is_file($file) ? (string) file_get_contents($file) : '';

        $start = strpos($existing, self::START);
        $end = strpos($existing, self::END);

        $marked = $start !== false && $end !== false && $end > $start;
        $result = match (true) {
            $marked => substr($existing, 0, $start) . $block . substr($existing, $end + strlen(self::END)),
            trim($existing) === '' => $block . "\n",
            default => rtrim($existing) . "\n\n" . $block . "\n",
        };

        file_put_contents($file, $result);

        return !$marked && trim($existing) !== '';
    }

    /**
     * The generated paths, between markers in the theme's .gitignore.
     *
     * @param list<Agent> $agents
     */
    private static function gitignore(array $agents): void
    {
        $file = Paths::base('.gitignore');
        $paths = ['/AGENTS.md'];
        foreach ($agents as $agent) {
            foreach ($agent->generated() as $path) {
                $paths[] = "/{$path}";
            }
        }

        $block = "# gaffer:ai (generated by `php gaffer ai:update`, never commit)\n" . implode("\n", array_unique($paths)) . "\n# gaffer:ai:end";
        $existing = is_file($file) ? (string) file_get_contents($file) : '';

        $result = preg_match('/^# gaffer:ai .*?^# gaffer:ai:end$/ms', $existing)
            ? (string) preg_replace('/^# gaffer:ai .*?^# gaffer:ai:end$/ms', $block, $existing)
            : rtrim($existing) . ($existing === '' ? '' : "\n\n") . $block . "\n";

        file_put_contents($file, $result);
    }

    private static function copy(string $from, string $to): void
    {
        mkdir($to, 0755, true);
        /** @var iterable<SplFileInfo> $items */
        $items = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($from, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::SELF_FIRST);
        foreach ($items as $item) {
            $path = $to . substr($item->getPathname(), strlen($from));
            $item->isDir() ? mkdir($path, 0755, true) : copy($item->getPathname(), $path);
        }
    }

    private static function remove(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }
        /** @var iterable<SplFileInfo> $items */
        $items = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
        foreach ($items as $item) {
            $item->isDir() ? rmdir($item->getPathname()) : unlink($item->getPathname());
        }
        rmdir($dir);
    }
}
